-- Remplissage de la table ainventions depuis data.js
-- Mis à jour le 23/08/2026 — 419 fiches.
-- Relançable sans doublon : les fiches existantes sont mises à jour.

insert into public.ainventions (slug, name, city) values
  ('2m-ain-energie-val-revermont', '2m Ain-Énergie', 'Val-Revermont'),
  ('accueil-can-ain-guereins', 'Accueil Can''Ain', 'Guéreins'),
  ('aeri-ain-danses-aeriennes-loyettes', 'Aeri''Ain Danses Aériennes', 'Loyettes'),
  ('aexalp-ain-culoz-beon', 'Aexalp Ain', 'Culoz-Béon'),
  ('afc-ain-formatic-virieu-le-grand', 'AFC Ain''Formatic', 'Virieu-le-Grand'),
  ('agriporc-ain-marsonnas', 'Agriporc''Ain', 'Marsonnas'),
  ('aides-ain-formatique-polliat', 'Aides Ain''Formatique', 'Polliat'),
  ('ain-2-3-salades-bourg-en-bresse', 'Ain 2 3 Salades', 'Bourg-en-Bresse'),
  ('ain-2-3-services-pont-de-vaux', 'Ain 2 3 Services', 'Pont-de-Vaux'),
  ('ain-2-jardinage-oyonnax', 'Ain 2 Jardinage', 'Oyonnax'),
  ('ain-appui-saint-denis-les-bourg', 'Ain Appui', 'Saint-Denis-lès-Bourg'),
  ('ain-auto-assistance-bourg-en-bresse', 'Ain Auto Assistance', 'Bourg-en-Bresse'),
  ('ain-bb-val-revermont', 'Ain BB', 'Val-Revermont'),
  ('ain-bien-etre-beynost', 'Ain Bien Être', 'Beynost'),
  ('ain-blanc-deux-freres-marboz', 'Ain Blanc Deux Frères', 'Marboz'),
  ('ain-bon-services-vernoux', 'Ain Bon Services', 'Vernoux'),
  ('ain-boost-office-bourg-en-bresse', 'Ain Boost''Office', 'Bourg-en-Bresse'),
  ('ain-brun-de-service-pizay', 'Ain Brun de Service', 'Pizay'),
  ('ain-capital-partners-bressolles', 'Ain Capital Partners', 'Bressolles'),
  ('ain-carrefour-d-europe-bourg-en-bresse', 'Ain Carrefour d''Europe', 'Bourg-en-Bresse'),
  ('ain-carrelages-chateau-gaillard', 'Ain Carrelages', 'Château-Gaillard'),
  ('ain-coeur-d-art-tenay', 'Ain Coeur d''Art', 'Tenay'),
  ('ain-corporation-civrieux', 'Ain Corporation', 'Civrieux'),
  ('ain-coup-de-main-francheleins', 'Ain Coup de Main', 'Francheleins'),
  ('ain-coup-de-pouce-biziat', 'Ain Coup de Pouce', 'Biziat'),
  ('ain-coup-de-pouce-saint-sorlin-en-bugey', 'Ain Coup de Pouce', 'Saint-Sorlin-en-Bugey'),
  ('ain-de-plus-saint-genis-pouilly', 'Ain de Plus', 'Saint-Genis-Pouilly'),
  ('ain-decor-port', 'Ain Décor', 'Port'),
  ('ain-delice-bourg-en-bresse', 'Ain Délice', 'Bourg-en-Bresse'),
  ('ain-desir-de-piscine-peronnas', 'Ain Désir de Piscine', 'Péronnas'),
  ('ain-fleurs-et-sens-mionnay', 'Ain Fleurs et Sens', 'Mionnay'),
  ('ain-fo-expertise-chateau-gaillard', 'Ain FO Expertise', 'Château-Gaillard'),
  ('ain-formation-performance-bourg-en-bresse', 'Ain Formation Performance', 'Bourg-en-Bresse'),
  ('ain-fusion-oyonnax', 'Ain Fusion', 'Oyonnax'),
  ('ain-habitat-bourg-en-bresse', 'Ain Habitat', 'Bourg-en-Bresse'),
  ('ain-max-d-h2o-saint-genis-sur-menthon', 'Ain Max d''H2O', 'Saint-Genis-sur-Menthon'),
  ('ain-moment-pour-jouer-peyrieu', 'Ain Moment pour Jouer', 'Peyrieu'),
  ('ain-p-tits-services-oyonnax', 'Ain P''tits Services', 'Oyonnax'),
  ('ain-pac-immo-bourg-en-bresse', 'Ain PAC Immo', 'Bourg-en-Bresse'),
  ('ain-paradis-vert-charnoz-sur-ain', 'Ain Paradis Vert', 'Charnoz-sur-Ain'),
  ('ain-petit-service-bourg-en-bresse', 'Ain Petit Service', 'Bourg-en-Bresse'),
  ('ain-portes-et-fenetres-montagnat', 'ain portes et Fenêtres', 'Montagnat'),
  ('ain-pose-vonnas', 'Ain Pose', 'Vonnas'),
  ('ain-pose-ta-fenetre-lagnieu', 'Ain Pose ta Fenêtre', 'Lagnieu'),
  ('ain-pour-tous-tous-pour-ain-bourg-en-bresse', 'Ain pour Tous, Tous pour Ain', 'Bourg-en-Bresse'),
  ('ain-pressions-bien-etre-villars-les-dombes', 'Ain Pressions Bien-Être', 'Villars-les-Dombes'),
  ('ain-pro-concept-druillat', 'Ain Pro Concept', 'Druillat'),
  ('ain-pro-fermeture-rignieux-le-franc', 'Ain Pro Fermeture', 'Rignieux-le-Franc'),
  ('ain-pro-renov-montracol', 'Ain Pro Renov''', 'Montracol'),
  ('ain-ratable-fermetures-chazey-sur-ain', 'Ain Ratable Fermetures', 'Chazey-sur-Ain'),
  ('ain-roc-belley', 'Ain Roc', 'Belley'),
  ('ain-services-particuliers-bourg-en-bresse', 'Ain Services Particuliers', 'Bourg-en-Bresse'),
  ('ain-services-pro-montluel', 'Ain Services Pro', 'Montluel'),
  ('ain-stall-chauffage-crans', 'Ain Stall Chauffage', 'Crans'),
  ('ain-team-conviction-montagnat', 'Ain Team Conviction', 'Montagnat'),
  ('ain-team-form-laiz', 'ain team Form''', 'Laiz'),
  ('ain-team-sheep-montreal-la-cluse', 'Ain Team Sheep', 'Montréal-la-Cluse'),
  ('ain-team-sport-tribu-ceyzeriat', 'Ain Team Sport Tribu', 'Ceyzériat'),
  ('ain-temps-de-jeux-bourg-en-bresse', 'Ain Temps de Jeux', 'Bourg-en-Bresse'),
  ('ain-terre-action-saint-cyr-sur-menthon', 'Ain Terre Action', 'Saint-Cyr-sur-Menthon'),
  ('ain-terre-pole-01-montagnat', 'Ain Terre Pole 01', 'Montagnat'),
  ('ain-thime-transport-villebois', 'Ain Thime Transport', 'Villebois'),
  ('ain-terieur-deco-chatillon-sur-chalaronne', 'Ain Térieur Déco', 'Châtillon-sur-Chalaronne'),
  ('ain-ventil-saint-denis-en-bugey', 'Ain Ventil', 'Saint-Denis-en-Bugey'),
  ('ain-zen-shiatsu-messimy-sur-saone', 'Ain Zen Shiatsu', 'Messimy-sur-Saône'),
  ('ain-elagage-bage-dommartin', 'Ain Élagage', 'Bâgé-Dommartin'),
  ('ain-cendie-elec-bourg-en-bresse', 'Ain''Cendie Élec', 'Bourg-en-Bresse'),
  ('ain-contournable-bourg-en-bresse', 'Ain''Contournable', 'Bourg-en-Bresse'),
  ('ain-coup-de-patte-chaneins', 'Ain''Coup de Patte', 'Chaneins'),
  ('ain-des-gonflables-haut-valromey', 'Ain''Des Gonflables', 'Haut-Valromey'),
  ('ain-dice-immobilier-miserieux', 'Ain''Dice Immobilier', 'Misérieux'),
  ('ain-dispensables-services-a-domicile-priay', 'AIN''DISPENSABLES ! SERVICES À DOMICILE', 'Priay'),
  ('ain-en-ferme-chazey-sur-ain', 'Ain''En Ferme', 'Chazey-sur-Ain'),
  ('ain-en-ferme-bocal-saint-sorlin-en-bugey', 'Ain''En Ferme - Bocal', 'Saint-Sorlin-en-Bugey'),
  ('ain-f-soins-sainte-julie', 'Ain''F Soins', 'Sainte-Julie'),
  ('ain-firmieres-amberieu-en-bugey', 'Ain''Firmières', 'Ambérieu-en-Bugey'),
  ('ain-firmieres-villieu-loyes-mollon-soins-a-domicile-villieu-loyes-mollon', 'Ain''Firmières Villieu-Loyes-Mollon : Soins à Domicile', 'Villieu-Loyes-Mollon'),
  ('ain-form-tion-lagnieu', 'Ain''Form@tion', 'Lagnieu'),
  ('ain-formation-climatique-chalamont', 'Ain''Formation Climatique', 'Chalamont'),
  ('ain-genierie-viriat', 'Ain''Génierie', 'Viriat'),
  ('ain-imal-bien-etre-polliat', 'Ain''Imal Bien-Être', 'Polliat'),
  ('ain-invest-bourg-en-bresse', 'Ain''Invest', 'Bourg-en-Bresse'),
  ('ain-ject-pro-nettoyage-peronnas', 'Ain''Ject Pro Nettoyage', 'Péronnas'),
  ('ain-pact-tp-premeyzel', 'Ain''Pact TP', 'Prémeyzel'),
  ('ain-pacte-bourg-en-bresse', 'Ain''Pacte', 'Bourg-en-Bresse'),
  ('ain-pec-nettoyage-dagneux', 'AIN''PEC NETTOYAGE', 'Dagneux'),
  ('ain-peccable-certines', 'Ain''Peccable', 'Certines'),
  ('ain-portance-valserhone', 'Ain''Portance', 'Valserhône'),
  ('ain-pression-truck-l-abergement-clemenciat', 'Ain''Pression Truck', 'L''Abergement-Clémenciat'),
  ('ain-prim-bourg-en-bresse', 'Ain''Prim', 'Bourg-en-Bresse'),
  ('ain-puls-gorrevod', 'Ain''Puls', 'Gorrevod'),
  ('ain-pulsion-cotiere-bmx-thil', 'Ain''Pulsion Côtière BMX', 'Thil'),
  ('ain-pulsion-parapente-val-revermont', 'Ain''Pulsion Parapente', 'Val-Revermont'),
  ('ain-s-temps-massage-feillens', 'Ain''S Temps Massage', 'Feillens'),
  ('ain-spiration-spa-arbent', 'Ain''Spiration Spa', 'Arbent'),
  ('ain-spire-oyonnax', 'Ain''Spire', 'Oyonnax'),
  ('ain-stall-leyment', 'Ain''Stall', 'Leyment'),
  ('ain-stall-pac-bressolles', 'Ain''Stall PAC', 'Bressolles'),
  ('ain-stant-douceur-montagnat', 'Ain''Stant Douceur', 'Montagnat'),
  ('ain-stant-famille-priay', 'Ain''stant Famille', 'Priay'),
  ('ain-stant-garden-saint-just', 'Ain''Stant Garden', 'Saint-Just'),
  ('ain-stant-pour-soi-belley', 'Ain''stant Pour Soi', 'Belley'),
  ('ain-stant-pour-soi-jasseron', 'Ain''stant Pour Soi', 'Jasseron'),
  ('ain-stant-reno-miribel', 'Ain''stant Réno', 'Miribel'),
  ('ain-stant-yoga-mionnay', 'Ain''Stant Yoga', 'Mionnay'),
  ('ain-stemps-photos-montrevel-en-bresse', 'Ain''Stemps Photos', 'Montrevel-en-Bresse'),
  ('ain-stinct-bike-bourg-en-bresse', 'Ain''Stinct Bike', 'Bourg-en-Bresse'),
  ('ain-stinctifs-villars-les-dombes', 'Ain''Stinctifs', 'Villars-les-Dombes'),
  ('ain-temporel-poncin', 'Ain''Temporel', 'Poncin'),
  ('ain-tendance-bureautique-saint-etienne-du-bois', 'Ain''Tendance Bureautique', 'Saint-Étienne-du-Bois'),
  ('ain-tension-electricite-cressin-rochefort', 'Ain''Tension Électricité', 'Cressin-Rochefort'),
  ('ain-ter-exter-ate-bourg-en-bresse', 'ain''ter exter (Ate)', 'Bourg-en-Bresse'),
  ('ain-terlude-en-bugey-champagne-en-valromey', 'Ain''terlude en Bugey', 'Champagne-en-Valromey'),
  ('ain-tegral-4x4-lagnieu', 'Ain''tégral 4x4', 'Lagnieu'),
  ('ain-tegral-land-lagnieu', 'Ain''Tégral Land', 'Lagnieu'),
  ('ain-tegration-reflexes-saint-genis-pouilly', 'Ain''Tégration Réflexes', 'Saint-Genis-Pouilly'),
  ('ain-2-3-sport-savigneux', 'AIN, 2, 3 Sport', 'Savigneux'),
  ('ain-form-tique-valserhone', 'Ain-Form@tique', 'Valserhône'),
  ('ain-formation-informatique-saint-jean-sur-reyssouze', 'Ain-Formation-Informatique', 'Saint-Jean-sur-Reyssouze'),
  ('ain-pact-vitrage-auto-oyonnax', 'Ain-Pact Vitrage Auto', 'Oyonnax'),
  ('ain-team-racing-ceyzeriat', 'Ain-Team-Racing', 'Ceyzériat'),
  ('aindolor-plateau-d-hauteville', 'Aindolor', 'Plateau d''Hauteville'),
  ('ainfinimentdrone-bettant', 'Ainfinimentdrone', 'Bettant'),
  ('ainfluen-sab-arbent', 'Ainfluen''Sab', 'Arbent'),
  ('ainflux-bourg-en-bresse', 'Ainflux', 'Bourg-en-Bresse'),
  ('ainflux-services-chevroux', 'Ainflux Services', 'Chevroux'),
  ('ainformatik-services-saint-julien-sur-veyle', 'Ainformatik-Services', 'Saint-Julien-sur-Veyle'),
  ('ainformatique-facile-val-revermont', 'Ainformatique Facile', 'Val-Revermont'),
  ('ainformatix-bourg-en-bresse', 'Ainformatix', 'Bourg-en-Bresse'),
  ('ainpact-saint-martin-du-mont', 'Ainpact', 'Saint-Martin-du-Mont'),
  ('ainpact-renov-serrieres-en-chautagne', 'Ainpact''Renov', 'Serrières-en-Chautagne'),
  ('ainpec-services-sainte-croix', 'Ainpec Services', 'Sainte-Croix'),
  ('ainpec-services-neuville-les-dames', 'Ainpec Services', 'Neuville-les-Dames'),
  ('ainpression-3d-valromey-sur-seran', 'Ainpression 3d', 'Valromey-sur-Séran'),
  ('ainrezo-certines', 'AinRezo', 'Certines'),
  ('ainrock-oyonnax', 'Ainrock', 'Oyonnax'),
  ('ainsol-hit-vaux-en-bugey', 'Ainsol Hit', 'Vaux-en-Bugey'),
  ('ainspiration-chocolat-feillens', 'Ainspiration Chocolat', 'Feillens'),
  ('ainstant-plaque-o-valserhone', 'Ainstant Plaque''O', 'Valserhône'),
  ('ainstant-animal-amberieu-en-bugey', 'Ainstant''Animal', 'Ambérieu-en-Bugey'),
  ('ainter-a-dom-ambronay', 'Ainter A Dom', 'Ambronay'),
  ('ainter-auto-thoiry', 'Ainter Auto', 'Thoiry'),
  ('ainter-deco-cessy', 'Ainter Déco', 'Cessy'),
  ('ainter-services-certines', 'Ainter Services', 'Certines'),
  ('ainter-services-a-la-personne-certines', 'Ainter Services à la Personne', 'Certines'),
  ('ainter-job-bourg-en-bresse', 'Ainter''Job', 'Bourg-en-Bresse'),
  ('ainter-pro-bourg-en-bresse', 'Ainter''Pro', 'Bourg-en-Bresse'),
  ('ainterconsulaire-bourg-en-bresse', 'Ainterconsulaire', 'Bourg-en-Bresse'),
  ('ainterface-habitat-amberieu-en-bugey', 'Ainterface-Habitat', 'Ambérieu-en-Bugey'),
  ('ainterim-oyonnax', 'Ainterim', 'Oyonnax'),
  ('ainterim-air-bourg-en-bresse', 'Ainterim''Air', 'Bourg-en-Bresse'),
  ('aintermetal-chatillon-sur-chalaronne', 'Aintermetal', 'Châtillon-sur-Chalaronne'),
  ('ainternet-services-atns-thil', 'Ainternet Services ATNS', 'Thil'),
  ('aintramuros-saint-julien-sur-veyle', 'Aintramuros', 'Saint-Julien-sur-Veyle'),
  ('aintranet-amberieu-en-bugey', 'Aintranet', 'Ambérieu-en-Bugey'),
  ('aintru-zion-bourg-en-bresse', 'Aintru-Zion', 'Bourg-en-Bresse'),
  ('ainventure-2000-amberieu-en-bugey', 'Ainventure 2000', 'Ambérieu-en-Bugey'),
  ('ainversion-parapente-val-revermont', 'Ainversion Parapente', 'Val-Revermont'),
  ('ainvestimmo-montagnat', 'Ainvestimmo', 'Montagnat'),
  ('alp-ain-taxi-seyssel', 'Alp''Ain Taxi', 'Seyssel'),
  ('amap-ain-stant-panier-amberieu-en-bugey', 'AMAP Ain''stant Panier', 'Ambérieu-en-Bugey'),
  ('amap-terre-ain-d-entente-champagne-en-valromey', 'AMAP Terre Ain d''Entente', 'Champagne-en-Valromey'),
  ('ambiance-jard-ain-amberieu-en-bugey', 'Ambiance Jard''Ain', 'Ambérieu-en-Bugey'),
  ('amenagements-ain-terieurs-bourg-en-bresse', 'Aménagements Ain''Térieurs', 'Bourg-en-Bresse'),
  ('api-ain-d-confrancon', 'Api Ain''D', 'Confrançon'),
  ('aqua-jard-ain-vaux-en-bugey', 'Aqua-Jard''Ain', 'Vaux-en-Bugey'),
  ('arts-cosmopolit-ain-bourg-en-bresse', 'Arts Cosmopolit''Ain', 'Bourg-en-Bresse'),
  ('association-cous-ain-jujurieux', 'Association Cous''Ain', 'Jujurieux'),
  ('association-de-communication-non-violente-de-l-ain-a-l-autre-oyonnax', 'Association de Communication Non-Violente de l''Ain à l''Autre', 'Oyonnax'),
  ('association-l-arlequ-ain-chazey-sur-ain', 'Association l''Arlequ''Ain', 'Chazey-sur-Ain'),
  ('association-maison-m-ain-tendue-plateau-d-hauteville', 'Association Maison M''Ain Tendue', 'Plateau d''Hauteville'),
  ('association-pl-ain-les-s-potes-plateau-d-hauteville', 'Association Pl''Ain les S''potes', 'Plateau d''Hauteville'),
  ('atelier-ain-plein-d-arts-neuville-sur-ain', 'Atelier Ain Plein d''Arts', 'Neuville-sur-Ain'),
  ('au-comptoir-des-pot-ain-champdor-corcelles', 'Au Comptoir des Pot''Ain', 'Champdor-Corcelles'),
  ('au-fil-de-l-ain-nantua', 'Au Fil de l''Ain', 'Nantua'),
  ('au-gourmand-ain-loyettes', 'Au Gourmand''Ain', 'Loyettes'),
  ('au-moul-ain-des-saveurs-ozan', 'Au Moul''Ain des Saveurs', 'Ozan'),
  ('au-p-tit-gr-ain-bourg-en-bresse', 'Au P''tit Gr''Ain', 'Bourg-en-Bresse'),
  ('au-va-et-vi-ain-bourg-en-bresse', 'Au Va et Vi''Ain', 'Bourg-en-Bresse'),
  ('auto-moto-ecole-formul-ain-attignat', 'Auto Moto École Formul''Ain', 'Attignat'),
  ('auto-n-ain-balan', 'Auto N Ain', 'Balan'),
  ('auto-ecole-formmul-ain-attignat', 'Auto École Formmul''Ain', 'Attignat'),
  ('ballad-ain-belley', 'Ballad''Ain', 'Belley'),
  ('bamb-ain-autos-bourg-en-bresse', 'Bamb''Ain Autos', 'Bourg-en-Bresse'),
  ('bamb-ain-et-compagnie-belley', 'Bamb''Ain et Compagnie', 'Belley'),
  ('bati-ain-goncalves-marboz', 'Bati''Ain Goncalves', 'Marboz'),
  ('benja-main-multiservices-bresse-vallons', 'Benja''Main Multiservices', 'Bresse Vallons'),
  ('bi-ain-services-montrevel-en-bresse', 'Bi''Ain Services', 'Montrevel-en-Bresse'),
  ('bi-ain-services-pro-montrevel-en-bresse', 'Bi''Ain Services Pro', 'Montrevel-en-Bresse'),
  ('bien-etre-can-ain-poncin', 'Bien Être Can''Ain', 'Poncin'),
  ('bio-jard-ain-peron', 'Bio Jard''Ain', 'Péron'),
  ('bistrot-1900-ain-pont-de-vaux', 'Bistrot 1900 Ain', 'Pont-de-Vaux'),
  ('bomat-ain-lent', 'Bomat''Ain', 'Lent'),
  ('bon-ain-spiration-ceyzeriat', 'Bon''Ain Spiration', 'Ceyzériat'),
  ('bouc-ain-martignat', 'Bouc''Ain', 'Martignat'),
  ('boyat-dominique-ainstant-bois-manziat', 'Boyat Dominique / Ainstant Bois', 'Manziat'),
  ('br-ain-de-malice-saint-martin-le-chatel', 'Br''Ain de Malice', 'Saint-Martin-le-Châtel'),
  ('br-ain-de-plomberie-attignat', 'Br''Ain de Plomberie', 'Attignat'),
  ('brain-ball-arboys-en-bugey', 'Brain Ball', 'Arboys-en-Bugey'),
  ('brasserie-l-ain-pression-villieu-loyes-mollon', 'Brasserie l''Ain Pression', 'Villieu-Loyes-Mollon'),
  ('bricol-ain-saint-just', 'Bricol''Ain', 'Saint-Just'),
  ('broc-ain-belley', 'Broc''Ain', 'Belley'),
  ('bugey-ain-terim-bellignat', 'Bugey Ain''Terim', 'Bellignat'),
  ('cabinet-ain-firmieres-valserhone', 'Cabinet Ain-Firmières', 'Valserhône'),
  ('cadol-ain-servignat', 'Cadol''Ain', 'Servignat'),
  ('can-ain-minet-neuville-les-dames', 'Can''Ain & Minet', 'Neuville-les-Dames'),
  ('can-ain-et-compagnie-champdor-corcelles', 'Can''Ain et Compagnie', 'Champdor-Corcelles'),
  ('cap-ain-cendie-chevroux', 'Cap Ain''Cendie', 'Chevroux'),
  ('carrel-ain-oyonnax', 'Carrel''Ain', 'Oyonnax'),
  ('centre-can-ain-fel-ain-illiat', 'Centre Can''Ain Fel''Ain', 'Illiat'),
  ('cercle-kaledoni-ain-amberieu-en-bugey', 'Cercle Kaledoni''Ain', 'Ambérieu-en-Bugey'),
  ('cheval-ain-transport-saint-julien-sur-reyssouze', 'Cheval Ain Transport', 'Saint-Julien-sur-Reyssouze'),
  ('cl-ain-d-oeil-priay', 'Cl''Ain d''Oeil', 'Priay'),
  ('cl-ain-d-oeil-pont-d-ain', 'Cl.Ain d''Oeil', 'Pont-d''Ain'),
  ('comedy-ain-saint-martin-du-frene', 'Comedy''Ain', 'Saint-Martin-du-Frêne'),
  ('concept-ainterieur-chatillon-sur-chalaronne', 'Concept''Ainterieur', 'Châtillon-sur-Chalaronne'),
  ('coop-ain-energie-trevoux', 'Coop''Ain Énergie', 'Trévoux'),
  ('cop-ain-de-trail-ornex', 'Cop''Ain de Trail', 'Ornex'),
  ('cote-jard-ain-baneins', 'Cote Jard''Ain', 'Baneins'),
  ('couleurs-d-ain-terieurs-hautecourt-romaneche', 'Couleurs d''Ain''Térieurs', 'Hautecourt-Romanèche'),
  ('cour-jard-ain-pont-de-veyle', 'Cour & Jard''Ain', 'Pont-de-Veyle'),
  ('cuma-l-ain-composte-servas', 'CUMA l''Ain Composte', 'Servas'),
  ('dans-mon-jard-ain-montagnat', 'Dans Mon Jard''Ain', 'Montagnat'),
  ('dem-ain-cormoranche-sur-saone', 'Dem''Ain', 'Cormoranche-sur-Saône'),
  ('des-bulles-dans-les-m-ain-blyes', 'Des Bulles dans les M''Ain', 'Blyes'),
  ('div-ain-immobilier-divonne-les-bains', 'Div''Ain Immobilier', 'Divonne-les-Bains'),
  ('dom-ain-services-confrancon', 'Dom''Ain Services', 'Confrançon'),
  ('domaine-des-ain-contournables-attignat', 'Domaine des Ain''contournables', 'Attignat'),
  ('domaine-du-tres-haut-montanges', 'Domaine du Tres-Haut', 'Montanges'),
  ('drn-magas-ain-guereins', 'DRN Magas''Ain', 'Guéreins'),
  ('drone-ain-ttitude-bourg-en-bresse', 'Drone Ain''Ttitude', 'Bourg-en-Bresse'),
  ('deco-jard-ain-beny', 'Déco Jard''Ain', 'Bény'),
  ('decoloint-ain-bourg-en-bresse', 'Décoloint''Ain', 'Bourg-en-Bresse'),
  ('ebullitions-canard-ain-pertinent-bourg-en-bresse', 'Ebullitions Canard Ain-Pertinent', 'Bourg-en-Bresse'),
  ('electrici-ain-valserhone', 'Electrici''Ain', 'Valserhône'),
  ('enfant-ain-ceyzeriat', 'Enfant''Ain', 'Ceyzériat'),
  ('entr-ain-culoz-beon', 'Entr''Ain', 'Culoz-Béon'),
  ('entre-mes-m-ain-saint-andre-sur-vieux-jonc', 'Entre Mes M''Ain', 'Saint-André-sur-Vieux-Jonc'),
  ('epicur-ain-saint-didier-de-formans', 'Epicur''Ain', 'Saint-Didier-de-Formans'),
  ('escargot-ain-marboz', 'Escargot''Ain', 'Marboz'),
  ('espaces-jard-ain-collonges', 'Espaces Jard''Ain', 'Collonges'),
  ('esprit-ain-dien-meximieux', 'Esprit Ain''Dien', 'Meximieux'),
  ('esprit-can-ain-blyes', 'Esprit Can''Ain', 'Blyes'),
  ('ess-ain-bourg-en-bresse', 'ESS''AIN', 'Bourg-en-Bresse'),
  ('extern-ain-paie-peronnas', 'Extern''Ain Paie', 'Péronnas'),
  ('fabi-ain-cycles-saint-andre-de-corcy', 'Fabi Ain Cycles', 'Saint-André-de-Corcy'),
  ('fleurs-de-l-ain-saint-andre-de-corcy', 'Fleurs de l''Ain', 'Saint-André-de-Corcy'),
  ('flocking-ain-stinct-confrancon', 'Flocking Ain''Stinct', 'Confrançon'),
  ('form-ain-maillat', 'Form''Ain', 'Maillat'),
  ('gites-au-soleil-jura-si-ain-mijoux', 'Gites au Soleil Jura-Si-Ain', 'Mijoux'),
  ('gr-ain-de-folie-maillat', 'Gr''Ain de Folie', 'Maillat'),
  ('graine-de-l-ain-farges', 'Graine de l''Ain', 'Farges'),
  ('graine-de-p-ain-peron', 'Graine de P''Ain', 'Péron'),
  ('graines-de-l-ain-bourg-en-bresse', 'Graines de l''Ain', 'Bourg-en-Bresse'),
  ('groupement-d-employeurs-du-jard-ain-pont-de-veyle', 'Groupement d''employeurs du Jard''Ain', 'Pont-de-Veyle'),
  ('huis-ainter-bourg-en-bresse', 'Huis Ainter', 'Bourg-en-Bresse'),
  ('idc-formal-ain-amberieu-en-bugey', 'IDC Formal''Ain', 'Ambérieu-en-Bugey'),
  ('idees-ain-portees-jasseron', 'Idees Ain Portees', 'Jasseron'),
  ('inst-ain-gourmand-pont-de-vaux', 'Inst''Ain Gourmand', 'Pont-de-Vaux'),
  ('jard-ain-beligneux', 'Jard''Ain', 'Béligneux'),
  ('jard-ain-concept-vandeins', 'Jard''Ain Concept', 'Vandeins'),
  ('jard-ain-service-toussieux', 'Jard''Ain Service', 'Toussieux'),
  ('jolie-m-ain-polliat', 'Jolie M''Ain', 'Polliat'),
  ('juste-ain-detail-saint-jean-sur-veyle', 'Juste Ain Detail', 'Saint-Jean-sur-Veyle'),
  ('kop-ain-basket-nurieux-volognat', 'Kop''Ain Basket', 'Nurieux-Volognat'),
  ('l-ain-avec-l-hote-chatenay', 'L''Ain Avec l''Hôte', 'Châtenay'),
  ('l-ain-burger-valromey-sur-seran', 'L''Ain Burger', 'Valromey-sur-Séran'),
  ('l-ain-color-blyes', 'L''Ain Color', 'Blyes'),
  ('l-ain-confort-table-confort', 'L''Ain Confort Table', 'Confort'),
  ('l-ain-contournable-saint-didier-sur-chalaronne', 'L''Ain Contournable', 'Saint-Didier-sur-Chalaronne'),
  ('l-ain-desirable-ceyzeriat', 'L''Ain Désirable', 'Ceyzériat'),
  ('l-ain-et-l-autre-virignin', 'L''Ain et l''Autre', 'Virignin'),
  ('l-ain-parfait-chatillon-en-michaille', 'L''Ain Parfait', 'Châtillon-en-Michaille'),
  ('l-ain-tres-table-jayat', 'L''Ain Très Table', 'Jayat'),
  ('l-ain-dispensable-jujurieux', 'L''Ain''dispensable', 'Jujurieux'),
  ('l-ain-stant-boheme-boyeux-saint-jerome', 'L''Ain''Stant Bohème', 'Boyeux-Saint-Jérôme'),
  ('l-ain-terface-amberieu-en-bugey', 'L''Ain-Terface', 'Ambérieu-en-Bugey'),
  ('l-ain-ventif-saint-trivier-sur-moignans', 'L''Ain-Ventif', 'Saint-Trivier-sur-Moignans'),
  ('l-ainconfortable-confort', 'L''Ainconfortable', 'Confort'),
  ('l-aincontournable-blyes', 'L''Aincontournable', 'Blyes'),
  ('l-ainpact-oyonnax', 'L''Ainpact', 'Oyonnax'),
  ('l-ainproviste-bourg-en-bresse', 'L''Ainproviste', 'Bourg-en-Bresse'),
  ('l-ainstant-sushis-pont-d-ain', 'L''Ainstant Sushis', 'Pont-d''Ain'),
  ('l-ainstant-velo-saint-benigne', 'L''Ainstant Velo', 'Saint-Bénigne'),
  ('l-ainstant-zen-isa-chateau-gaillard', 'L''Ainstant Zen Isa', 'Château-Gaillard'),
  ('l-aintensite-du-bugey-conand', 'L''Aintensite du Bugey', 'Conand'),
  ('l-aintimiste-poncin', 'L''AinTimiste', 'Poncin'),
  ('l-americ-ain-massignieu-de-rives', 'L''Americ''Ain', 'Massignieu-de-Rives'),
  ('l-europeain-bourg-en-bresse', 'L''Europeain', 'Bourg-en-Bresse'),
  ('l-eveil-des-coq-ain-saint-trivier-de-courtes', 'L''Éveil des Coq''Ain', 'Saint-Trivier-de-Courtes'),
  ('la-ferme-des-petits-galop-ain-courtes', 'La Ferme des Petits Galop''Ain', 'Courtes'),
  ('la-m-ain-verte-jayat', 'La M''Ain Verte', 'Jayat'),
  ('lb-ainformatique-saint-etienne-du-bois', 'LB Ainformatique', 'Saint-Étienne-du-Bois'),
  ('le-bon-mat-ain-saint-jean-de-niost', 'Le Bon Mat''Ain', 'Saint-Jean-de-Niost'),
  ('le-chat-l-ain-villette-sur-ain', 'Le Chat''L''Ain', 'Villette-sur-Ain'),
  ('le-clos-onjard-ain-bage-dommartin', 'Le Clos Onjard''Ain', 'Bâgé-Dommartin'),
  ('le-coin-des-cop-ain-blyes', 'Le Coin des Cop Ain', 'Blyes'),
  ('le-coq-au-v-ain-biziat', 'Le Coq au V''Ain', 'Biziat'),
  ('le-coq-ain-haut-valromey', 'Le Coq''Ain', 'Haut-Valromey'),
  ('le-coup-de-m-ain-meximieux', 'Le Coup de M''Ain', 'Meximieux'),
  ('le-gourmand-ain-cormoranche-sur-saone', 'Le Gourmand''Ain', 'Cormoranche-sur-Saône'),
  ('le-jard-ain-foret-hautecourt-romaneche', 'Le Jard''Ain Forêt', 'Hautecourt-Romanèche'),
  ('le-mandar-ain-trevoux', 'Le Mandar''Ain', 'Trévoux'),
  ('le-saint-germ-ain-saint-denis-en-bugey', 'Le Saint Germ''Ain', 'Saint-Denis-en-Bugey'),
  ('les-ain-trepides-balan', 'Les Ain Trépides', 'Balan'),
  ('les-ain-gredients-sainte-julie', 'Les Ain''Grédients', 'Sainte-Julie'),
  ('les-ain-trepides-en-rose-oyonnax', 'Les Ain''trépides en Rose', 'Oyonnax'),
  ('les-ainrockuptibles-montmerle-sur-saone', 'Les Ainrockuptibles', 'Montmerle-sur-Saône'),
  ('les-ballad-ain-de-l-accordeon-belley', 'Les Ballad''Ain de l''Accordéon', 'Belley'),
  ('les-bamb-ain-de-la-combe-vieu-d-izenave', 'Les Bamb''Ain de la Combe', 'Vieu-d''Izenave'),
  ('les-brodequ-ain-artemare', 'Les Brodequ''Ain', 'Artemare'),
  ('les-cop-ain-d-abord-saint-etienne-du-bois', 'Les Cop''Ain d''Abord', 'Saint-Étienne-du-Bois'),
  ('les-cop-ain-d-attelage-corbonod', 'Les Cop''Ain d''Attelage', 'Corbonod'),
  ('les-cop-ains-loyettes', 'Les Cop''Ains', 'Loyettes'),
  ('les-cop-ain-formatique-meillonnas', 'Les Cop.Ain.Formatique', 'Meillonnas'),
  ('les-electrici-ain-martignat', 'Les Electrici''Ain', 'Martignat'),
  ('les-frang-ain-villars-les-dombes', 'Les Frang''Ain', 'Villars-les-Dombes'),
  ('les-gourmands-d-ain-ii-sainte-euphemie', 'Les Gourmands d''Ain II', 'Sainte-Euphémie'),
  ('les-jard-ain-bugistes-lhuis', 'Les Jard''Ain Bugistes', 'Lhuis'),
  ('les-jard-ain-de-vincent-villette-sur-ain', 'Les Jard''Ain de Vincent', 'Villette-sur-Ain'),
  ('les-jarres-d-ain-marsonnas', 'Les Jarres d''Ain', 'Marsonnas'),
  ('les-legumes-du-jard-ain-pont-de-veyle', 'Les Légumes du Jard''Ain', 'Pont-de-Veyle'),
  ('les-pilot-ain-ramasse', 'Les Pilot''Ain', 'Ramasse'),
  ('m-ain-dans-la-main-amberieu-en-bugey', 'M''Ain dans la Main', 'Ambérieu-en-Bugey'),
  ('m-ain-dans-la-main-oyonnax', 'M''Ain dans la Main', 'Oyonnax'),
  ('m-ain-tenant-culoz-beon', 'M''Ain Tenant', 'Culoz-Béon'),
  ('machines-a-coudre-rhone-alp-ain-bourg-en-bresse', 'Machines a Coudre Rhone Alp''Ain', 'Bourg-en-Bresse'),
  ('maitre-grillad-ain-hautecourt-romaneche', 'Maitre Grillad''Ain', 'Hautecourt-Romanèche'),
  ('mam-les-cop-ain-d-abord-magnieu', 'MAM Les Cop''Ain d''Abord', 'Magnieu'),
  ('mat-ain-plomberie-sainte-julie', 'Mat''Ain Plomberie', 'Sainte-Julie'),
  ('meca-sport-terr-ain-marsonnas', 'Meca Sport Terr''Ain', 'Marsonnas'),
  ('mfm-consult-ain-jassans-riottier', 'MFM Consult Ain', 'Jassans-Riottier'),
  ('micro-creche-les-lut-ain-arbent', 'Micro Crèche les Lut''Ain', 'Arbent'),
  ('micro-creche-les-lut-ain-izernore-izernore', 'Micro-crèche Les Lut''Ain Izernore', 'Izernore'),
  ('mil-et-ain-services-chaveyriat', 'Mil et Ain Services', 'Chaveyriat'),
  ('mille-et-ain-papillons-rignieux-le-franc', 'Mille et Ain Papillons', 'Rignieux-le-Franc'),
  ('mille-et-ain-services-saint-martin-le-chatel', 'Mille et Ain Services', 'Saint-Martin-le-Châtel'),
  ('montbel-ain-coligny', 'Montbel''Ain', 'Coligny'),
  ('moto-club-le-balad-ain-cruzilles-les-mepillat', 'Moto Club le Balad''Ain', 'Cruzilles-lès-Mépillat'),
  ('moto-loisir-gaillard-ain-chateau-gaillard', 'Moto Loisir Gaillard''Ain', 'Château-Gaillard'),
  ('my-chauffeur-numero-ain-villieu-loyes-mollon', 'My Chauffeur Numéro Ain', 'Villieu-Loyes-Mollon'),
  ('nature-ain-pact-artemare', 'Nature Ain''Pact', 'Artemare'),
  ('nos-douces-m-ain-montreal-la-cluse', 'Nos Douces M''Ain', 'Montréal-la-Cluse'),
  ('numero-ain-immo-biziat', 'Numéro Ain Immo', 'Biziat'),
  ('numero-ain-service-villars-les-dombes', 'Numéro Ain Service', 'Villars-les-Dombes'),
  ('o-cop-ain-gourmand-belley', 'O Cop''Ain Gourmand', 'Belley'),
  ('ofemin-ain-lagnieu', 'Ofemin''Ain', 'Lagnieu'),
  ('oh-diablot-ain-belley', 'Oh Diablot''Ain', 'Belley'),
  ('paint-a-gone-jujurieux', 'Paint''A Gone', 'Jujurieux'),
  ('papilles-ain-solites-bourg-en-bresse', 'Papilles Ain''Solites', 'Bourg-en-Bresse'),
  ('parapent-ain-val-revermont', 'Parapent''ain', 'Val-Revermont'),
  ('patur-ain-chateau-gaillard', 'Patur Ain', 'Château-Gaillard'),
  ('paul-position-ain-viriat', 'Paul Position Ain', 'Viriat'),
  ('pep-ain-rossillon', 'Pep''Ain', 'Rossillon'),
  ('perrin-entreti-ain-simandre-sur-suran', 'Perrin Entreti''Ain', 'Simandre-sur-Suran'),
  ('pl-ain-d-energie-amberieu-en-bugey', 'Pl''Ain d''Énergie', 'Ambérieu-en-Bugey'),
  ('pl-ain-jeux-amberieu-en-bugey', 'Pl''Ain Jeux', 'Ambérieu-en-Bugey'),
  ('pl-ain-vol-viriat', 'Pl''Ain Vol', 'Viriat'),
  ('plant-ain-coligny', 'Plant''Ain', 'Coligny'),
  ('pole-ain-formatique-oyonnax', 'Pole Ain''Formatique', 'Oyonnax'),
  ('poney-bamb-ain-villette-sur-ain', 'Poney Bamb''Ain', 'Villette-sur-Ain'),
  ('pouss-ain-manziat', 'Pouss''Ain', 'Manziat'),
  ('rallye-franj-ain-bourg-en-bresse', 'Rallye Franj''Ain', 'Bourg-en-Bresse'),
  ('renov-ain-grieges', 'Renov''Ain', 'Grièges'),
  ('repar-ain-velo-montrevel-en-bresse', 'Repar''Ain Velo', 'Montrevel-en-Bresse'),
  ('rob-ain-des-bois-ambronay', 'Rob''Ain des Bois', 'Ambronay'),
  ('rock-ain-blues-collonges', 'Rock Ain Blues', 'Collonges'),
  ('rock-ain-festival-sainte-julie', 'Rock Ain Festival', 'Sainte-Julie'),
  ('rod-ain-saint-maurice-de-gourdans', 'Rod''Ain', 'Saint-Maurice-de-Gourdans'),
  ('rom-ain-auto-ecole-bourg-en-bresse', 'Rom''Ain Auto-École', 'Bourg-en-Bresse'),
  ('rom-ain-meca-courmangoux', 'Rom''Ain Meca', 'Courmangoux'),
  ('ronde-et-rebelle-ain-fograph-curtafond', 'Ronde et Rebelle - Ain''Fograph''', 'Curtafond'),
  ('renovation-style-anci-ain-peronnas', 'Rénovation Style Anci''Ain', 'Péronnas'),
  ('reseau-ain-dependance-bourg-en-bresse', 'Réseau Ain Dépendance', 'Bourg-en-Bresse'),
  ('s-c-i-les-cous-ain-charnoz-sur-ain', 'S.c.i. les Cous Ain', 'Charnoz-sur-Ain'),
  ('sarl-ain-bon-nettoyage-saint-nizier-le-bouchoux', 'SARL Ain Bon Nettoyage', 'Saint-Nizier-le-Bouchoux'),
  ('sarl-ain-pro-saint-nizier-le-bouchoux', 'SARL Ain Pro', 'Saint-Nizier-le-Bouchoux'),
  ('sarl-bod-ain-constructions-valserhone', 'SARL Bod''Ain Constructions', 'Valserhône'),
  ('sarl-equ-ain-e-m-l-s-miribel', 'SARL Equ''Ain E.M.L.S.', 'Miribel'),
  ('savoies-ain-construction-belley', 'Savoies''Ain Construction', 'Belley'),
  ('sci-ain-avenir-immo-lapeyrouse', 'SCI Ain Avenir Immo', 'Lapeyrouse'),
  ('sci-du-moul-ain-pizay', 'SCI du Moul''Ain', 'Pizay'),
  ('scm-ain-firmier-belley', 'SCM Ain''Firmier', 'Belley'),
  ('secretaire-ain-dependante-villieu-loyes-mollon', 'Secrétaire Ain''Dépendante', 'Villieu-Loyes-Mollon'),
  ('select-evainement-coligny', 'Select Evainement', 'Coligny'),
  ('smart-ainfo-attignat', 'Smart''Ainfo', 'Attignat'),
  ('solutr-ain-loyettes', 'Solutr''Ain', 'Loyettes'),
  ('souti-ain-scolaire-oyonnax', 'Souti''Ain Scolaire', 'Oyonnax'),
  ('taxi-malain-bourg-en-bresse', 'Taxi Malain', 'Bourg-en-Bresse'),
  ('tendance-p-ainture-bourg-en-bresse', 'Tendance P''Ainture', 'Bourg-en-Bresse'),
  ('terr-ain-paintball-saint-laurent-sur-saone', 'Terr''Ain''Paintball', 'Saint-Laurent-sur-Saône'),
  ('terr-ain-azur-coligny', 'Terr(Ain) Azur', 'Coligny'),
  ('terre-ain-promotion-feillens', 'Terre Ain Promotion', 'Feillens'),
  ('tourneux-sylv-ain-platrerie-peinture-injoux-genissiat', 'Tourneux Sylv''Ain Platrerie Peinture', 'Injoux-Génissiat'),
  ('tous-pour-un-ain-pour-tous-saint-genis-pouilly', 'Tous pour Un Ain pour Tous', 'Saint-Genis-Pouilly'),
  ('tout-en-m-ain-tenay', 'Tout en M''Ain', 'Tenay'),
  ('trail-ain-dventre-varambon', 'Trail Ain''Dventre', 'Varambon'),
  ('trempl-ain-agro-bourg-en-bresse', 'Trempl''Ain Agro', 'Bourg-en-Bresse'),
  ('un-br-ain-de-bonheur-ceignes', 'Un Br''Ain de Bonheur', 'Ceignes'),
  ('un-parr-ain-emploi-mionnay', 'Un Parr''Ain Emploi', 'Mionnay'),
  ('verdain-atelier-journans', 'Verdain Atelier', 'Journans'),
  ('vision-ain-terieur-ceyzerieu', 'Vision Ain''Térieur', 'Ceyzérieu'),
  ('vit-ain-plombier-tossiat', 'Vit''Ain Plombier', 'Tossiat'),
  ('elec-renov-ain-matafelon-granges', 'Élec Renov''Ain', 'Matafelon-Granges'),
  ('epicerie-gr-ain-de-sel-saint-just', 'Épicerie Gr''Ain de Sel', 'Saint-Just'),
  ('agencement-ain-terieur-pont-d-ain', 'Agencement Ain''Térieur', 'Pont-d''Ain'),
  ('ain-croyable-com-trevoux', 'Ain''croyable Com', 'Trévoux'),
  ('ain-croyable-noel-bourg-en-bresse', 'Ain''croyable Noël', 'Bourg-en-Bresse'),
  ('ain-dispensables-villieu-loyes-mollon', 'Ain''dispensables !', 'Villieu-Loyes-Mollon'),
  ('ain-stant-panier-amberieu-en-bugey', 'Ain''stant Panier', 'Ambérieu-en-Bugey'),
  ('aindice-montrevel-en-bresse', 'Aindice', 'Montrevel-en-Bresse'),
  ('ainfluence-construction-saint-denis-en-bugey', 'Ainfluence Construction', 'Saint-Denis-en-Bugey'),
  ('ainpacte-notaires-associes-lagnieu', 'Ainpacte Notaires Associés', 'Lagnieu'),
  ('amap-la-jur-ainsienne-bellignat', 'AMAP La Jur''Ainsienne', 'Bellignat'),
  ('aux-kotas-finland-ain-izieu', 'Aux Kotas Finland''Ain', 'Izieu'),
  ('l-ain-stant-yourte-boyeux-saint-jerome', 'L''Ain''stant Yourte', 'Boyeux-Saint-Jérôme'),
  ('l-olainpe-tossiat', 'L''Olainpe', 'Tossiat'),
  ('le-clan-fel-ain-bourg-en-bresse', 'Le Clan Fél''Ain', 'Bourg-en-Bresse'),
  ('tonn-ain-hebergement-ain-solite-journans', 'Tonn''Ain Hébergement Ain''Solite', 'Journans')
on conflict (slug) do update set name = excluded.name, city = excluded.city;
